apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-monitor
  labels:
    app: metrics-monitor
    
spec:
  endpoints:
    - port: metrics
      interval: 15s
      path: /actuator/prometheus     
  selector:
    matchLabels:
      app: myapp
  namespaceSelector:
    matchNames:
      - back
