{
 "title": "OtusTestDashBoard",
 "time": { "from": "2022-08-04T05:49:56.941Z", "to": "2022-08-04T07:02:20.743Z" },
 "panels": [
  {
   "title": "Postgres available connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((sum(pg_settings_max_connections) by (server) - sum(pg_settings_superuser_reserved_connections) by (server)) - sum(pg_stat_activity_count) by (server))"
    }
   ]
  },
  {
   "title": "Max transaction duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (server) (pg_stat_activity_max_tx_duration)"
    }
   ]
  },
  {
   "title": "Postgres storage usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (server) (pg_database_size_bytes)"
    }
   ]
  },
  {
   "title": "Postgres available storage by mountpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum by (mountpoint) (node_filesystem_free_bytes)"
    }
   ]
  },
  {
   "title": "Cpu by pods usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"backend.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory by pods usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"backend.*\"})"
    }
   ]
  },
  {
   "title": "50 quantile by uri",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,uri) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[1m])))"
    }
   ]
  },
  {
   "title": "Nginx 50 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_service) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"backend-service\"}[1m])))"
    }
   ]
  },
  {
   "title": "95 quantile by uri",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,uri) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[1m])))"
    }
   ]
  },
  {
   "title": "nginx 95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, exported_service) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"backend-service\"}[1m])))"
    }
   ]
  },
  {
   "title": "99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,uri) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[1m])))"
    }
   ]
  },
  {
   "title": "Nginx 99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_service) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"backend-service\"}[1m])))"
    }
   ]
  },
  {
   "title": "RPS by URI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{uri=~\"/api/.*\", service=\"backend-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 11, "y": 44 },
   "targets": [
    {
     "expr": "sum by (exported_service) (rate(nginx_ingress_controller_requests{exported_service=\"backend-service\"}[1m]))"
    }
   ]
  },
  {
   "title": "500 request by uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (uri) (http_server_requests_seconds_count{uri=~\"/api/.*\", status=\"500\"})"
    }
   ]
  },
  {
   "title": "Total 500 request nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 50 },
   "targets": [
    {
     "expr": "sum by (exported_service) (nginx_ingress_controller_requests{exported_service=\"backend-service\", status=\"500\"})"
    }
   ]
  }
 ]
}