apiVersion: batch/v1
kind: Job
metadata:
  name: migrationmain
  namespace: {{ .Values.namespace }}
  labels:
    app: job
spec:
  template:
    metadata:
      name: migration
      labels:
        app: job
    spec:
      restartPolicy: Never
      containers:
        - name: insert
          env:
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: otus-app-config
                  key: rds-host-name
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: otus-app-config
                  key: rds-user-name
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: otus-app-config
                  key: rds-db-name
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otus-app-secrets
                  key: psqluserpass
          image: postgres:11
          command:
            - sh
            - "-c"
            - |
              PGPASSWORD=$PASSWORD psql -d $DATABASE -U $DB_USER -h $DATABASE_URI  <<'EOF'
                CREATE SEQUENCE IF NOT EXISTS users_id_seq;
                CREATE TABLE IF NOT EXISTS users
                  (
                  id bigint default nextval('users_id_seq'::regclass) not null
                  primary key,
                  username varchar(255),
                  firstname varchar(255),
                  lastname varchar(255),
                  email varchar(255),
                  phone varchar(255)
                  );
              EOF
  backoffLimit: 0